CREATE TABLE TRADING_TARGETS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DETECT_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    SYMBOL_CODE VARCHAR2(20) NOT NULL,
    SYMBOL_NAME VARCHAR2(100) NOT NULL,
    STRATEGY_CODE VARCHAR2(10) NOT NULL,
    DETECT_PRICE NUMBER NOT NULL,
    NOTES VARCHAR2(500)
);

COMMENT ON TABLE TRADING_TARGETS IS '주식 자동매매 타점 포착 로그 테이블';
COMMENT ON COLUMN TRADING_TARGETS.ID IS '고유 식별자';
COMMENT ON COLUMN TRADING_TARGETS.DETECT_TIME IS '타점 포착 시간';
COMMENT ON COLUMN TRADING_TARGETS.SYMBOL_CODE IS '종목코드';
COMMENT ON COLUMN TRADING_TARGETS.SYMBOL_NAME IS '종목명';
COMMENT ON COLUMN TRADING_TARGETS.STRATEGY_CODE IS '적중된 전략코드 (예: A-1, B-3)';
COMMENT ON COLUMN TRADING_TARGETS.DETECT_PRICE IS '포착 당시 가격';
COMMENT ON COLUMN TRADING_TARGETS.NOTES IS '추가 참고 사항';
